src/MarvinLabs/AcraServerBundle/Entity/Crash.php
<?php

namespace MarvinLabs\AcraServerBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Crashes
 *
 * @ORM\Table(name="acra_crash")
 * @ORM\Entity(repositoryClass="MarvinLabs\AcraServerBundle\Entity\CrashRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Crash
{
	public static $STATUS_NEW 		= 0;
	public static $STATUS_FIXED 	= 1;
	
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var datetime $createdAt
     *
     * @ORM\Column(name="created_at", type="datetime", nullable=false)
     */
    private $createdAt;

    /**
     * @var integer
     *
     * @ORM\Column(name="status", type="integer", nullable=false)
     */
    private $status;

    /**
     * @var string
     *
     * @ORM\Column(name="issue_id", type="string", length=32, nullable=false)
     */
    private $issueId;

    /**
     * @var string
     *
     * @ORM\Column(name="report_id", type="text", nullable=false)
     */
    private $reportId;

    /**
     * @var string
     *
     * @ORM\Column(name="app_version_code", type="text", nullable=false)
     */
    private $appVersionCode;

    /**
     * @var string
     *
     * @ORM\Column(name="app_version_name", type="text", nullable=false)
     */
    private $appVersionName;

    /**
     * @var string
     *
     * @ORM\Column(name="package_name", type="text", nullable=false)
     */
    private $packageName;

    /**
     * @var string
     *
     * @ORM\Column(name="file_path", type="text", nullable=true)
     */
    private $filePath;

    /**
     * @var string
     *
     * @ORM\Column(name="phone_model", type="text", nullable=true)
     */
    private $phoneModel;

    /**
     * @var string
     *
     * @ORM\Column(name="android_version", type="text", nullable=true)
     */
    private $androidVersion;

    /**
     * @var string
     *
     * @ORM\Column(name="build", type="text", nullable=true)
     */
    private $build;

    /**
     * @var string
     *
     * @ORM\Column(name="brand", type="text", nullable=true)
     */
    private $brand;

    /**
     * @var string
     *
     * @ORM\Column(name="product", type="text", nullable=true)
     */
    private $product;

    /**
     * @var integer
     *
     * @ORM\Column(name="total_mem_size", type="integer", nullable=true)
     */
    private $totalMemSize;

    /**
     * @var integer
     *
     * @ORM\Column(name="available_mem_size", type="integer", nullable=true)
     */
    private $availableMemSize;

    /**
     * @var string
     *
     * @ORM\Column(name="custom_data", type="text", nullable=true)
     */
    private $customData;

    /**
     * @var string
     *
     * @ORM\Column(name="stack_trace", type="text", nullable=true)
     */
    private $stackTrace;

    /**
     * @var string
     *
     * @ORM\Column(name="initial_configuration", type="text", nullable=true)
     */
    private $initialConfiguration;

    /**
     * @var string
     *
     * @ORM\Column(name="crash_configuration", type="text", nullable=true)
     */
    private $crashConfiguration;

    /**
     * @var string
     *
     * @ORM\Column(name="display", type="text", nullable=true)
     */
    private $display;

    /**
     * @var string
     *
     * @ORM\Column(name="user_comment", type="text", nullable=true)
     */
    private $userComment;

    /**
     * @var datetime
     *
     * @ORM\Column(name="user_app_start_date", type="datetime", nullable=true)
     */
    private $userAppStartDate;

    /**
     * @var datetime
     *
     * @ORM\Column(name="user_crash_date", type="datetime", nullable=true)
     */
    private $userCrashDate;

    /**
     * @var string
     *
     * @ORM\Column(name="dumpsys_meminfo", type="text", nullable=true)
     */
    private $dumpsysMeminfo;

    /**
     * @var string
     *
     * @ORM\Column(name="dropbox", type="text", nullable=true)
     */
    private $dropbox;

    /**
     * @var string
     *
     * @ORM\Column(name="logcat", type="text", nullable=true)
     */
    private $logcat;

    /**
     * @var string
     *
     * @ORM\Column(name="eventslog", type="text", nullable=true)
     */
    private $eventslog;

    /**
     * @var string
     *
     * @ORM\Column(name="radiolog", type="text", nullable=true)
     */
    private $radiolog;

    /**
     * @var string
     *
     * @ORM\Column(name="is_silent", type="text", nullable=true)
     */
    private $isSilent;

    /**
     * @var string
     *
     * @ORM\Column(name="device_id", type="text", nullable=true)
     */
    private $deviceId;

    /**
     * @var string
     *
     * @ORM\Column(name="installation_id", type="text", nullable=true)
     */
    private $installationId;

    /**
     * @var string
     *
     * @ORM\Column(name="user_email", type="text", nullable=true)
     */
    private $userEmail;

    /**
     * @var string
     *
     * @ORM\Column(name="device_features", type="text", nullable=true)
     */
    private $deviceFeatures;

    /**
     * @var string
     *
     * @ORM\Column(name="environment", type="text", nullable=true)
     */
    private $environment;

    /**
     * @var string
     *
     * @ORM\Column(name="settings_global", type="text", nullable=true)
     */
    private $settingsGlobal;

    /**
     * @var string
     *
     * @ORM\Column(name="settings_system", type="text", nullable=true)
     */
    private $settingsSystem;

    /**
     * @var string
     *
     * @ORM\Column(name="settings_secure", type="text", nullable=true)
     */
    private $settingsSecure;

    /**
     * @var string
     *
     * @ORM\Column(name="shared_preferences", type="text", nullable=true)
     */
    private $sharedPreferences;

    /**
     * @var string
     *
     * @ORM\Column(name="media_codec_list", type="text", nullable=true)
     */
    private $mediaCodecList;

    /**
     * @var string
     *
     * @ORM\Column(name="thread_details", type="text", nullable=true)
     */
    private $threadDetails;

    /**
     * @var string
     *
     * @ORM\Column(name="application_log", type="text", nullable=true)
     */
    private $applicationLog;

    /**
     * Constructor
     */
    public function __construct()
    {
    	$this->setCreatedAt(new \DateTime(null, new \DateTimeZone('UTC')));
    	$this->setStatus(self::$STATUS_NEW);
    }

    /**
     * Set threadDetails
     *
     * @param string $threadDetails
     * @return Crash
     */
    public function setThreadDetails($threadDetails)
    {
        $this->threadDetails = $threadDetails;
    
        return $this;
    }

    /**
     * Get threadDetails
     *
     * @return string
     */
    public function getThreadDetails()
    {
        return $this->threadDetails;
    }

    /**
     * Set applicationLog
     *
     * @param string applicationLog
     * @return Crash
     */
    public function setApplicationLog($applicationLog)
    {
        $this->applicationLog = $applicationLog;
    
        return $this;
    }

    /**
     * Get applicationLog
     *
     * @return string
     */
    public function getApplicationLog()
    {
        return $this->applicationLog;
    }

    /**
     * Set mediaCodecList
     *
     * @param string $createdAt
     * @return Crash
     */
    public function setMediaCodecList($mediaCodecList)
    {
        $this->mediaCodecList = $mediaCodecList;
    
        return $this;
    }

    /**
     * Get mediaCodecList
     *
     * @return string
     */
    public function getMediaCodecList()
    {
        return $this->mediaCodecList;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Crash
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    
        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set status
     *
     * @param integer $status
     * @return Crash
     */
    public function setStatus($status)
    {
        $this->status = $status;
    
        return $this;
    }

    /**
     * Get status
     *
     * @return integer 
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Get status
     *
     * @return integer 
     */
    public function getStatusAsString()
    {
        switch ($this->status) {
        	case self::$STATUS_NEW: 	return 'new';
        	case self::$STATUS_FIXED: 	return 'new';
        	default: 					return 'unknwown';
        }
    }

    /**
     * Set issueId
     *
     * @param string $issueId
     * @return Crash
     */
    public function setIssueId($issueId)
    {
        $this->issueId = $issueId;
    
        return $this;
    }

    /**
     * Get issueId
     *
     * @return string 
     */
    public function getIssueId()
    {
        return $this->issueId;
    }

    /**
     * Set reportId
     *
     * @param string $reportId
     * @return Crash
     */
    public function setReportId($reportId)
    {
        $this->reportId = $reportId;
    
        return $this;
    }

    /**
     * Get reportId
     *
     * @return string 
     */
    public function getReportId()
    {
        return $this->reportId;
    }

    /**
     * Set appVersionCode
     *
     * @param string $appVersionCode
     * @return Crash
     */
    public function setAppVersionCode($appVersionCode)
    {
        $this->appVersionCode = $appVersionCode;
    
        return $this;
    }

    /**
     * Get appVersionCode
     *
     * @return string 
     */
    public function getAppVersionCode()
    {
        return $this->appVersionCode;
    }

    /**
     * Set appVersionName
     *
     * @param string $appVersionName

src/MarvinLabs/AcraServerBundle/Controller/CrashController.php
<?php

namespace MarvinLabs\AcraServerBundle\Controller;

use Doctrine\ORM\Mapping\Entity;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;

use MarvinLabs\AcraServerBundle\Entity\Crash;
use MarvinLabs\AcraServerBundle\DataFixtures\LoadFixtureData;

class CrashController extends Controller
{
	// TODO Disable in PROD environment
// 	public function generateTestDataAction()
// 	{	
//   		$doctrine = $this->getDoctrine()->getManager();
		
//   		$fixtureDataLoader = new LoadFixtureData();
//   		$fixtures = $fixtureDataLoader->load($doctrine);

//   		return new Response( var_dump($fixtures) );
// 	}
	
	/**
	 * Add a crash to the DB and send a notification to the crash admin
	 * 
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function addAction()
	{	
    	$crash = $this->newCrashFromRequest($this->getRequest());

       	// Persist crash
  		$doctrine = $this->getDoctrine()->getManager();
		$doctrine->persist($crash);
   		$doctrine->flush();
   		
   		// Send notification email
		$this->sendNewCrashNotification(
				$this->get('mailer'),
				$this->get('twig'),
				$this->container->getParameter('notifications_from'),
				$this->container->getParameter('notifications_to'),
				$crash
			);
   		
		return new Response( '' );
	}
    
    /**
     * Send an email notification about a new crash
     */
    private function sendNewCrashNotification($mailer, $twig, $from, $to, $crash)
    {
    	$message = \Swift_Message::newInstance()
	    	->setFrom($from)
	    	->setTo($to)
	    	->setSubject(sprintf(
	            	'[Acra Server] New crash for your application %s',
	    			$crash->getPackageName())
	    		)
	        ->setBody(
	            $twig
	    			->loadTemplate('MLabsAcraServerBundle:Notifications:crash_notification_body.html.twig')
	                ->render(array('crash' => $crash))
	            );
	    		
    	$mailer->send($message);
    }
    
    /**
     * Build a crash from the parameters passed to the request
     * 
     * @return \MarvinLabs\AcraServerBundle\Entity\Crash
     */
    private function newCrashFromRequest($request)
    {
    	$requestData = $request->request;
    	
    	$crash = new Crash();
    	$crash->setAndroidVersion($requestData->get('ANDROID_VERSION', null));
    	$crash->setAppVersionCode($requestData->get('APP_VERSION_CODE', null));
    	$crash->setAppVersionName($requestData->get('APP_VERSION_NAME', null));
    	$crash->setApplicationLog($requestData->get('APPLICATION_LOG', null));
    	$crash->setAvailableMemSize($requestData->get('AVAILABLE_MEM_SIZE', null));
    	$crash->setBrand($requestData->get('BRAND', null));
    	$crash->setBuild($requestData->get('BUILD', null));
    	$crash->setCrashConfiguration($requestData->get('CRASH_CONFIGURATION', null));
    	$crash->setCustomData($requestData->get('CUSTOM_DATA', null));
    	$crash->setDeviceFeatures($requestData->get('DEVICE_FEATURES', null));
    	$crash->setDeviceId($requestData->get('DEVICE_ID', null));
    	$crash->setDisplay($requestData->get('DISPLAY', null));
    	$crash->setDropbox($requestData->get('DROPBOX', null));
    	$crash->setDumpsysMeminfo($requestData->get('DUMPSYS_MEMINFO', null));
    	$crash->setEnvironment($requestData->get('ENVIRONMENT', null));
    	$crash->setEventsLog($requestData->get('EVENTSLOG', null));
    	$crash->setFilePath($requestData->get('FILE_PATH', null));
    	$crash->setInitialConfiguration($requestData->get('INITIAL_CONFIGURATION', null));
    	$crash->setInstallationId($requestData->get('INSTALLATION_ID', null));
    	$crash->setIsSilent($requestData->get('IS_SILENT', null));
    	$crash->setLogcat($requestData->get('LOGCAT', null));
    	$crash->setMediaCodecList($requestData->get('MEDIA_CODEC_LIST', null));
    	$crash->setPackageName($requestData->get('PACKAGE_NAME', null));
    	$crash->setPhoneModel($requestData->get('PHONE_MODEL', null));
    	$crash->setProduct($requestData->get('PRODUCT', null));
    	$crash->setRadioLog($requestData->get('RADIOLOG', null));
    	$crash->setReportId($requestData->get('REPORT_ID', null));
    	$crash->setSettingsGlobal($requestData->get('SETTINGS_GLOBAL', null));
    	$crash->setSettingsSecure($requestData->get('SETTINGS_SECURE', null));
    	$crash->setSettingsSystem($requestData->get('SETTINGS_SYSTEM', null));
    	$crash->setSharedPreferences($requestData->get('SHARED_PREFERENCES', null));
    	$crash->setStackTrace($requestData->get('STACK_TRACE', null));
    	$crash->setThreadDetails($requestData->get('THREAD_DETAILS', null));
    	$crash->setTotalMemSize($requestData->get('TOTAL_MEM_SIZE', null));
    	$crash->setUserComment($requestData->get('USER_COMMENT', null));
    	$crash->setUserEmail($requestData->get('USER_EMAIL', null));
    	
    	$tmpDateTime = new \DateTime( $requestData->get('USER_APP_START_DATE', null) );
    	$crash->setUserAppStartDate($tmpDateTime);

    	$tmpDateTime = new \DateTime( $requestData->get('USER_CRASH_DATE', null) );
    	$crash->setUserCrashDate($tmpDateTime);
    	
    	return $crash;
    }
}

src/MarvinLabs/AcraServerBundle/Resources/views/Crash/details.html.twig
{% extends 'MLabsAcraServerBundle::layout.html.twig' %}

{% import 'MLabsAcraServerBundle::cards.html.twig' as cards %}
{% import _self as fields %}


{% macro echo(title, value, test, value_wrapper, outer_tag) %}
	{% if test | default(value) %}	
		<{{ outer_tag | default('li') }} class="field">
			<strong class="label">{{ title }}</strong>: <{{value_wrapper | default('span')}} class="value">{{ value }}</{{value_wrapper | default('span')}}>
		</{{ outer_tag | default('li') }}>
	{% endif %}	
{% endmacro %}


{% block main %}


<section class="card-container crash-header">
	<h2>Crash #{{ crash.id }}</h2>
	
	<ul>
		{{ fields.echo('Package', crash.packageName) }}
		{{ fields.echo('Version', "#{ crash.appVersionName } ~ #{ crash.appVersionCode }", crash.appVersionName) }}
		{{ fields.echo('Submitted', "#{crash.createdAt | date('Y-m-d H:i:s')} (UTC)", crash.createdAt) }}
		{{ fields.echo('Status', crash.statusAsString) }}
		{{ fields.echo('User comment', crash.userComment) }}
		{{ fields.echo('User email', crash.userEmail) }}
		{{ fields.echo('App start', crash.userAppStartDate) }}
		{{ fields.echo('App crash', crash.userCrashDate) }}
	</ul>
</section>

<section class="crash-header">
	<div id="statistics-tabs" class="tab-container">				
		<ul class="nav">
	    	<li class="tab first"><a href="#distribution" class="current">Distribution</a></li>
            <li class="tab last"><a href="#evolution">Evolution</a></li>
	    </ul>
		
	    <div class="content">		
			<div id="distribution">
				<div id="crash-app-versions" class="graph-container half-width">
					<div class="graph"></div>
					<h4 class="title">Application versions</h4>
				</div>
				<div id="crash-android-versions" class="graph-container half-width">
					<div class="graph"></div>
					<h4 class="title">Android versions</h4>
				</div>
			</div>
			<div id="evolution">
				<div id="crash-in-time" class="graph-container full-width">
					<div class="graph"></div>
					<h4 class="title">Number of crashes with time</h4>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="crash-details">
	<div id="details-tabs" class="tab-container">				
		<ul class="nav">
	    	<li class="tab first"><a href="#stacktrace" class="current">Stacktrace</a></li>
            <li class="tab"><a href="#device">Device</a></li>
            <li class="tab"><a href="#android">Android</a></li>
            <li class="tab"><a href="#logs">Logs</a></li>
            <li class="tab"><a href="#settings">Settings</a></li>
            <li class="tab"><a href="#configuration">Configuration</a></li>
            <li class="tab last"><a href="#other">Other</a></li>
	    </ul>
		
	    <div class="tab-content">		
			<ul id="stacktrace">
				{{ fields.echo('Summary', crash.shortStackTrace, crash.shortStackTrace, 'pre') }}
				{{ fields.echo('Full', crash.stackTrace, crash.stackTrace, 'pre') }}
			</ul>
			 
			<ul id="device" class="hide">
				{{ fields.echo('Model', "#{ crash.brand }, #{ crash.phoneModel }", crash.brand) }}
				{{ fields.echo('Product code', crash.product) }}
				{{ fields.echo('Total memory', crash.totalMemSize | bfos_format_bytes, crash.totalMemSize) }}
				{{ fields.echo('Available memory', crash.availableMemSize | bfos_format_bytes, crash.availableMemSize) }}
				{{ fields.echo('Display', crash.display, crash.display, 'pre') }}
				{{ fields.echo('Features', crash.deviceFeatures, crash.deviceFeatures, 'pre') }}
				{{ fields.echo('Device ID', crash.deviceId, crash.deviceId, 'pre') }}
			</ul>
			
			<ul id="android" class="hide">
				{{ fields.echo('Version', crash.androidVersion) }}
				{{ fields.echo('Build details', crash.build, crash.build, 'pre') }}
			</ul>	
			
			<ul id="logs" class="hide">
				{{ fields.echo('logcat', crash.logcat, crash.logcat, 'pre') }}
				{{ fields.echo('eventslog', crash.eventslog, crash.eventslog, 'pre') }}
				{{ fields.echo('radiolog', crash.radiolog, crash.radiolog, 'pre') }}
				{{ fields.echo('applicationLog', crash.applicationLog, crash.applicationLog, 'pre') }}
			</ul>	
			
			<ul id="settings" class="hide">
				{{ fields.echo('Global', crash.settingsGlobal, crash.settingsGlobal, 'pre') }}
				{{ fields.echo('System', crash.settingsSystem, crash.settingsSystem, 'pre') }}
				{{ fields.echo('Secure', crash.settingsSecure, crash.settingsSecure, 'pre') }}
			</ul>
			
			<ul id="configuration" class="hide">
				{{ fields.echo('initialConfiguration', crash.initialConfiguration, crash.initialConfiguration, 'pre') }}
				{{ fields.echo('crashConfiguration', crash.crashConfiguration, crash.crashConfiguration, 'pre') }}
			</ul>	
			
			<ul id="other" class="hide">
				{{ fields.echo('File path', crash.filePath) }}
				{{ fields.echo('customData', crash.customData, crash.customData, 'pre') }}
				{{ fields.echo('dumpsysMeminfo', crash.dumpsysMeminfo, crash.dumpsysMeminfo, 'pre') }}
				{{ fields.echo('dropbox', crash.dropbox, crash.dropbox, 'pre') }}
				{{ fields.echo('isSilent', crash.isSilent, crash.isSilent, 'pre') }}
				{{ fields.echo('installationId', crash.installationId, crash.installationId, 'pre') }}
				{{ fields.echo('environment', crash.environment, crash.environment, 'pre') }}
				{{ fields.echo('sharedPreferences', crash.sharedPreferences, crash.sharedPreferences, 'pre') }}
				{{ fields.echo('mediaCodecList', crash.mediaCodecList, crash.mediaCodecList, 'pre') }}
				{{ fields.echo('threadDetails', crash.threadDetails, crash.threadDetails, 'pre') }}
			</ul>	 
	    </div>
	</div> 
</section>

{% endblock %}

{% block javascripts %}
    // The data for the charts
    var pieChartOptions = { 
   			series: {
	        	pie: {
	            	innerRadius: 0.5,
	            	show: true
	        	}
	    	}
	    };
	    
    var lineGraphOptions = { 
			xaxis: {
				mode: "time",
				minTickSize: [1, "day"],
				min: 1014937200000,
				max: 1199142000000,
				twelveHourClock: false
			}
	    };
	    
    var appVersionsData = [
		    {
			    label: "1.0",
    			data: 10
			},
		    {
			    label: "2.0",
    			data: 40
			},
		    {
			    label: "3.0",
    			data: 20
			},
		    {
			    label: "4.0",
    			data: 30
			},
		];
	    
    var androidVersionsData = [
		    {
			    label: "2.2",
    			data: 60
			},
		    {
			    label: "2.3",
    			data: 20
			},
		    {
			    label: "4.1",
    			data: 10
			},
		    {
			    label: "4.2.1",
    			data: 5
			},
		    {
			    label: "4.2.2",
    			data: 5
			},
		];
	    
    var timeData = [[
		    [1014937200000, 373.81], [1017612000000, 374.93], [1020204000000, 375.58], 
		    [1022882400000, 375.44], [1025474400000, 373.86], [1028152800000, 371.77], 
		    [1030831200000, 370.73], [1033423200000, 370.50], [1036105200000, 372.18], 
		    [1038697200000, 373.70], [1041375600000, 374.92], [1044054000000, 375.62], 
		    [1046473200000, 376.51], [1049148000000, 377.75], [1051740000000, 378.54], 
		    [1054418400000, 378.20], [1057010400000, 376.68], [1059688800000, 374.43], 
		    [1062367200000, 373.11], [1064959200000, 373.10], [1067641200000, 374.77], 
		    [1070233200000, 375.97], [1072911600000, 377.03], [1075590000000, 377.87], 
		    [1078095600000, 378.88], [1080770400000, 380.42], [1083362400000, 380.62], 
		    [1086040800000, 379.70], [1088632800000, 377.43], [1091311200000, 376.32], 
		    [1093989600000, 374.19], [1096581600000, 374.47], [1099263600000, 376.15], 
		    [1101855600000, 377.51], [1104534000000, 378.43], [1107212400000, 379.70], 
		    [1109631600000, 380.92], [1112306400000, 382.18], [1114898400000, 382.45], 
		    [1117576800000, 382.14], [1120168800000, 380.60], [1122847200000, 378.64], 
		    [1125525600000, 376.73], [1128117600000, 376.84], [1130799600000, 378.29], 
		    [1133391600000, 380.06], [1136070000000, 381.40], [1138748400000, 382.20], 
		    [1141167600000, 382.66], [1143842400000, 384.69], [1146434400000, 384.94], 
		    [1149112800000, 384.01], [1151704800000, 382.14], [1154383200000, 380.31], 
		    [1157061600000, 378.81], [1159653600000, 379.03], [1162335600000, 380.17], 
		    [1164927600000, 381.85], [1167606000000, 382.94], [1170284400000, 383.86], 
		    [1172703600000, 384.49], [1175378400000, 386.37], [1177970400000, 386.54], 
		    [1180648800000, 385.98], [1183240800000, 384.36], [1185919200000, 381.85], 
		    [1188597600000, 380.74], [1191189600000, 381.15], [1193871600000, 382.38], 
		    [1196463600000, 383.94], [1199142000000, 385.44]
		]];
    
    function redrawActiveTabCharts($, onlyActiveTab) {
   		if (typeof(onlyActiveTab)==='undefined') onlyActiveTab = true;
    	
    	if (onlyActiveTab) {
    		var activeTab = $(".tab-container").tabs( "option", "active" );
	       	if (activeTab==0) {	
			    $.plot("#crash-app-versions .graph", appVersionsData, pieChartOptions);
			    $.plot("#crash-android-versions .graph", androidVersionsData, pieChartOptions);
	       	} else if (activeTab==1) {
				$.plot("#crash-in-time .graph", timeData, lineGraphOptions);
	       	}	
       	} else {
		    $.plot("#crash-app-versions .graph", appVersionsData, pieChartOptions);
		    $.plot("#crash-android-versions .graph", androidVersionsData, pieChartOptions);
			$.plot("#crash-in-time .graph", timeData, lineGraphOptions);
       	}
    }
    
    $(document).ready(function(){ 	    
	    // Tab handling
	    var globalTabOptions = {
		        hide: { effect: "fade", duration: 300 },
		        show: { effect: "fade", duration: 300 },
		        
		       	// Following is to fix the page jump
		       	// see: http://stackoverflow.com/questions/243794/jquery-ui-tabs-causing-screen-to-jump
				select: function(event, ui) {
					jQuery(this).css('height', jQuery(this).height());
					jQuery(this).css('overflow', 'hidden');
				},
				show: function(event, ui) {
					jQuery(this).css('height', 'auto');
					jQuery(this).css('overflow', 'visible');
				}
			};
		var graphTabOptions = $.extend(globalTabOptions, {
		        activate: function( event, ui ) {
		        	redrawActiveTabCharts($);	
		        },
		        create: function( event, ui ) {
		        	redrawActiveTabCharts($, false);	
		        }
	        });
	    $("#details-tabs").tabs(globalTabOptions);
	    $("#statistics-tabs").tabs(graphTabOptions);
	    
	    // Redraw charts when window is resized
	    $(window).resize(function() {
	    	redrawActiveTabCharts($);	
		});
	});
{% endblock %}

src/MarvinLabs/AcraServerBundle/Resources/views/Crash/list.html.twig
{% extends 'MLabsAcraServerBundle::layout.html.twig' %}

{% block main %}

<section class="crash-list">
	<h2>{{ crashNum }} crashes</h2>

{% if crashes %}
	<table>
		<thead>
			{% block table_headers %}
			<tr>
				<th>Id</th>
				<th>Created</th>
				<th>Package</th>
				<th>App version</th>
				<th>Android version</th>
				<th></th>
			</tr>
			{% endblock %}
		</thead>
		<tbody>
		{% for c in crashes %}
			<tr>
				<td class="id">#{{ c.id }}</td>
				<td class="created-at">{{ c.createdAt | date('d/m/Y H:i:s') }} (UTC)</td>
				<td class="package-name">{{ c.packageName }}</td>
				<td class="app-version">{{ c.appVersionName }}</td>
				<td class="android-version">{{ c.androidVersion }}</td>
				<td class="action-link"><a href="{{ path('_crash_details', {'id': c.id}) }}" class="primary-button">Details</a></td>
			</tr>
		{% endfor %}
		</tbody>
		<tfoot>
			{{ block('table_headers') }}
		</tfoot>
	</table>
	
	{% include 'MLabsAcraServerBundle::pagination.html.twig' with {
	    currentFilters: { },
	    currentPage: page,
	    paginationPath: "_crash_list",
	    lastPage: totalPages,
	    showAlwaysFirstAndLast: false
	} only %}
	
{% else %}
	<p>No crashes here</p>
{% endif %}
</section>

{% endblock %}